version: '3.5'

services:
  workout_tracker:
    build:
      dockerfile: workout-tracker.dockerfile
      context: .
    ports:
      - '8001:8001'
    environment:
      MONGO_URI: 'mongodb://mongo:27017/?uuidRepresentation=standard'
    volumes:
      - ./:/srv
    entrypoint: uvicorn main:app --reload --port 8001 --host 0.0.0.0

  mongo:
    image: mongo

networks:
  default:
    name: workout_app_test_network
